EVENT_TYPE = {
    "SerialPurchased": "Serial Purchased",
    "SerialDelivered": "Serial Delivered",
    "SerialReturned": "Serial Returned",
    "SerialTransferCreated": "Serial Transfer Created",
    "SerialTransferAccepted": "Serial Transfer Accepted",
    "SerialTransferRejected": "Serial Transfer Rejected",
    "MaterialReceipt": "Material Receipt",
    "MaterialIssue": "Material Issue",
    "RnD_PRODUCTS": "R&D Product",
    "SENT_TO_IT_AND_NETWORK_SECTION": "Sent to IT & Network Section",
    "SENT_TO_PRINTER_IPG_SECTION": "Sent to Printer (IPG) Section ",
    "SENT_TO_SUPPORT_LENOVO_SECTION": "Sent to Support Section",
    "RECEIVED_FROM_CUSTOMER": "Received from Customer",
    "RECEIVED_FROM_BRANCH": "Received from Branch",
    "WORK_IN_PROGRESS": "Work in Progress",
    "TRANSFERRED": "Transferred",
    "SOLVED": "Solved - Repairing done",
    "TO_REPLACE": "Unsolved - To Replace",
    "UNSOLVED": "Unsolved - Return to Owner",
    "DELIVER_TO_CUSTOMER": "Deliver to Customer",
    "SENT_TO_ENG_DEPT": "Sent to Eng. Dept",
    "READY_TO_DELIVERED": "Ready to Deliver",
    "SENT_TO_REPAIR_DEPT": "Sent to Repair Section",
}
