name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use for the workflow"
        required: true
        default: "arif"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the triggered branch (arif or user-specified branch)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      # Run SonarQube scan
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Uncomment to fail the job when the Quality Gate is red
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
